from sqlalchemy import Column, String, Date, Float
from sqlalchemy.dialects.postgresql import UUID
from app.models.BaseClasses import Base
import uuid


class PchRXClaim(Base):
    __tablename__ = "pch_rx_claim"
    __table_args__ = {"schema": "wpo"}

    pk_id = Column(
        UUID(as_uuid=True), 
        primary_key=True, 
        default=uuid.uuid4,
        nullable=False
    )
    vbc_run_id = Column(String)
    plan_dim_ck = Column(String)
    post_period = Column(String)
    plan_desc = Column(String)
    contract_dim_ck = Column(String)
    entity_id = Column(String)
    reporting_year = Column(String)
    entity_dim_ck = Column(String)
    entity_name = Column(String)
    skey = Column(String)
    member_amisys_nbr = Column(String)
    fifteenth_date_dim_ck = Column(String)
    year_mo = Column(String)
    medicaid_nbr = Column(String)
    medicare_id = Column(String)
    name_suffix = Column(String)
    last_name = Column(String)
    first_name = Column(String)
    name_prefix = Column(String)
    middle_name = Column(String)
    first_m_last_name = Column(String)
    sex = Column(String)
    birth_date_dim_ck = Column(String)
    mbr_age = Column(String)
    product_line = Column(String)
    coverage_level = Column(String)
    mcc = Column(String)
    service_trans_ck = Column(String)
    pharmacy_claim_ck = Column(String)
    paid_amt = Column(String)
    drug_desc = Column(String)
    plan_nbr = Column(String)
    reversal_ind = Column(String)
    national_drug_code_nbr = Column(String)
    refill_nbr = Column(String)
    prescription_nbr = Column(String)
    dispensed_quantity = Column(String)
    days_supply = Column(String)
    ingredient_cost_amt = Column(String)
    dispensed_fee_amt = Column(String)
    group_nbr = Column(String)
    refills_authorized = Column(String)
    fill_date_dim_ck = Column(String)
    prescription_date_dim_ck = Column(String)
    gcn_nbr = Column(String)
    formulary_ind = Column(String)
    place_of_svc_code = Column(String)
    drug_type_code = Column(String)
    drug_type_desc = Column(String)
    brand_generic_ind = Column(String)
    consolidated_generic_brand_ind = Column(String)
    pcp_irs_name = Column(String)
    pcp_irs_nbr = Column(String)
    pcp_county_code = Column(String)
    pcp_npi = Column(String)
    pcp_prov_nbr = Column(String)
    pcp_prac_first_name = Column(String)
    pcp_prac_last_name = Column(String)
    pcp_prac_middle_name = Column(String)
    pcp_prac_title_name = Column(String)
    pcp_inst_name = Column(String)
    prescribing_prov_dim_ck = Column(String)
    prescribing_prov_nbr = Column(String)
    prescribing_institution_name = Column(String)
    prescribing_prov_prac_last_name = Column(String)
    prescribing_prov_prac_first_name = Column(String)
    prescribing_prov_prac_middle_name = Column(String)
    prescribing_prov_prac_title_name = Column(String)
    pharmacy_prov_dim_ck = Column(String)
    pharmacy_nbr = Column(String)
    pharmacy = Column(String)
    prescribing_npi = Column(String)
    prescribing_npi_name = Column(String)
    rate_cell_full_desc = Column(String)
    prescribing_taxonomy_code = Column(String)
    prescribing_taxonomy_desc = Column(String)
    county = Column(String)
    attribution_name = Column(String)
    contract_reporting_year = Column(String)
    report_date = Column(String)
    company_id = Column(String)
    carrier_id = Column(String)
    load_date = Column(String)
    status = Column(String)
    source = Column(String)
    source_type = Column(String)
    
    def __repr__(self):
        values = {c.name: getattr(self, c.name) for c in self.__table__.columns}
        return f"<PchRXClaim {values}>"