--- Patient Header Table
CREATE TABLE "EDI_Tebra".patient_header (
	"source" varchar(100) DEFAULT 'Tebra'::character varying NOT NULL,
	pat_id varchar(500) NULL,
	client_id int4 NULL,
	group_id int4 NULL,
	practice_id int4 NULL,
	sub_lnam varchar(500) NOT NULL,
	pat_fnam varchar(500) NOT NULL,
	middle_name varchar(500) NULL,
	prefix text NULL,
	suffix text NULL,
	pat_gender varchar(500) NULL,
	pat_dob varchar(500) NOT NULL,
	active bool DEFAULT true NULL,
	patient_full_name varchar(500) NULL,
	age varchar(10) NULL,
	ssn text NULL,
	marital_status text NULL,
	medical_record_number varchar(500) NULL,
	pat_email varchar(500) NULL,
	pat_contact varchar(500) NULL,
	work_phone varchar(500) NULL,
	work_phone_ext text NULL,
	mobile_phone varchar(500) NULL,
	mobile_phone_ext text NULL,
	home_phone varchar(500) NULL,
	home_phone_ext text NULL,
	pat_contact_consent bool NULL,
	pat_contact_method varchar(500) NULL,
	emergency_name varchar(500) NULL,
	emergency_phone varchar(500) NULL,
	emergency_phone_ext text NULL,
	pat_addr1 varchar(500) NULL,
	pat_addr2 varchar(500) NULL,
	pat_city varchar(500) NULL,
	pat_st varchar(500) NULL,
	pat_zip varchar(500) NULL,
	country varchar(500) NULL,
	employer_name varchar(500) NULL,
	employment_status varchar(100) NULL,
	primary_care_physician_id text NULL,
	primary_care_physician_full_name varchar(500) NULL,
	referring_provider_id text NULL,
	referring_provider_full_name varchar(500) NULL,
	referral_source varchar(500) NULL,
	collection_category_name varchar(500) NULL,
	total_balance numeric(18, 2) NULL,
	patient_balance numeric(18, 2) NULL,
	insurance_balance numeric(18, 2) NULL,
	alert_message text NULL,
	alert_show_patient_details bool NULL,
	alert_show_encounters bool NULL,
	alert_show_payments bool NULL,
	alert_show_statements bool NULL,
	alert_show_appointments bool NULL,
	alert_show_claims bool NULL,
	last_appointment_date text NULL,
	last_encounter_date text NULL,
	last_payment_date text NULL,
	last_statement_date text NULL,
	default_case_id text NULL,
	default_case_name varchar(500) NULL,
	default_case_description text NULL,
	default_service_location_id text NULL,
	default_service_location_name varchar(500) NULL,
	default_rendering_provider_id text NULL,
	default_rendering_provider_name varchar(500) NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	patient_header_id uuid DEFAULT gen_random_uuid() NOT NULL,
	loaded_at timestamp NULL,
	source_id varchar(500) NULL,
	pcn varchar(100) NULL,
	pcn_original varchar(500) NULL,
	is_self_pay bool DEFAULT false NOT NULL,
	CONSTRAINT patient_header_pkey PRIMARY KEY (patient_header_id),
	CONSTRAINT patient_header_client_id_fkey FOREIGN KEY (client_id) REFERENCES "EDI_Tebra".client(client_id),
	CONSTRAINT patient_header_group_id_fkey FOREIGN KEY (group_id) REFERENCES "EDI_Tebra"."group"(id),
	CONSTRAINT patient_header_practice_id_fkey FOREIGN KEY (practice_id) REFERENCES "EDI_Tebra".practice(id)
);

-- Table Triggers

create trigger tr_assign_pcn_original_after_insert after
insert
    on
    "EDI_Tebra".patient_header for each row execute function fn_assign_pcn_original_after_insert();
create trigger tr_generate_pcn before
insert
    on
    "EDI_Tebra".patient_header for each row execute function fn_generate_pcn_trigger();




--- Patient Coverage Table
CREATE TABLE "EDI_Tebra".patient_coverages (
	id serial4 NOT NULL,
	"source" varchar(100) DEFAULT 'Tebra'::character varying NOT NULL,
	client_id int4 NULL,
	group_id int4 NULL,
	practice_id int4 NULL,
	pat_id varchar(500) NULL,
	pat_source varchar(100) NOT NULL,
	pat_sub_lnam varchar(500) NOT NULL,
	pat_fnam varchar(500) NOT NULL,
	pat_dob varchar(500) NOT NULL,
	cov_status varchar(500) NULL,
	cov_type varchar(500) NULL,
	cov_car_id varchar(500) NULL,
	cov_car_nam varchar(500) NULL,
	cov_car_type varchar(500) NULL,
	cov_rel varchar(500) NULL,
	cov_sub_id varchar(500) NULL,
	cov_dep_id varchar(500) NULL,
	cov_start_date varchar(500) NULL,
	cov_end_date varchar(500) NULL,
	insurance_type varchar(1000) NULL,
	company_id text NULL,
	company_name varchar(500) NULL,
	policy_number varchar(500) NULL,
	group_number varchar(500) NULL,
	copay numeric(18, 4) NULL,
	deductible numeric(18, 4) NULL,
	effective_start_date text NULL,
	effective_end_date text NULL,
	patient_relationship_to_insured varchar(10) NULL,
	insured_full_name varchar(500) NULL,
	insured_id_number varchar(500) NULL,
	insured_ssn varchar(500) NULL,
	insured_dob text NULL,
	insured_gender varchar(500) NULL,
	insured_address1 varchar(500) NULL,
	insured_address2 varchar(500) NULL,
	insured_city varchar(500) NULL,
	insured_state varchar(500) NULL,
	insured_zip varchar(500) NULL,
	insured_country varchar(500) NULL,
	insured_notes text NULL,
	plan_id text NULL,
	plan_name varchar(500) NULL,
	plan_address1 varchar(500) NULL,
	plan_address2 varchar(500) NULL,
	plan_city varchar(500) NULL,
	plan_state varchar(500) NULL,
	plan_zip varchar(1000) NULL,
	plan_country varchar(500) NULL,
	plan_phone text NULL,
	plan_phone_ext text NULL,
	plan_fax text NULL,
	plan_fax_ext text NULL,
	plan_adjuster_name varchar(500) NULL,
	created_at timestamp DEFAULT now() NOT NULL,
	updated_at timestamp DEFAULT now() NOT NULL,
	cov_dep_name varchar(500) NULL,
	patient_header_id uuid NULL,
	active bool DEFAULT true NOT NULL,
	CONSTRAINT patient_coverages_pkey PRIMARY KEY (id),
	CONSTRAINT patient_coverages_patient_header_fk FOREIGN KEY (patient_header_id) REFERENCES "EDI_Tebra".patient_header(patient_header_id)
);
CREATE INDEX idx_patient_coverages_patient_header_id_cov_car_nam ON "EDI_Tebra".patient_coverages USING btree (patient_header_id, cov_car_nam) WHERE (cov_car_nam IS NOT NULL);