import uuid
from sqlalchemy import Column, String, Boolean, DateTime, text as sa_text, ForeignKey
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
from app.models.BaseClasses import Base

class Agents(Base):
    __tablename__ = "lup_agents"
    __table_args__ = {"schema": "wpo"}

    pk_id = Column(UNIQUEIDENTIFIER, primary_key=True, default=uuid.uuid4)

    company_id = Column(String)
    company_name = Column(String)
    owner = Column(String)
    fein = Column(String)
    indiana = Column(String)
    bday = Column(String)
    languages = Column(String)
    gender = Column(String)
    shop_date_2022 = Column(String)
    department = Column(String)
    assistant = Column(String)
    currency = Column(String)
    permission_to_text = Column(String)
    overrides1 = Column(String)
    healthsherpa_purl = Column(String)
    uhone = Column(String)
    status = Column(String)
    assignee = Column(String)
    first_visited_url = Column(String)
    negative_touch_point_score = Column(String)
    do_not_call = Column(String)
    agility_dmp = Column(String)
    california = Column(String)
    mississippi = Column(String)
    appointagents_com_subdomain = Column(String)
    illinois = Column(String)
    rhode_island = Column(String)
    bank_account_type = Column(String)
    georgia = Column(String)
    maryland = Column(String)
    idaho = Column(String)
    touch_point_score = Column(String)
    verified_date = Column(String)
    number_of_chats = Column(String)
    connecture_purl = Column(String)
    oklahoma = Column(String)
    other_zip = Column(String)
    mailing_street = Column(String)
    average_time_spent_minutes = Column(String)
    arkansas = Column(String)
    washington = Column(String)
    skype_id = Column(String)
    phone_extension = Column(String)
    ahip_date_2023 = Column(String)
    missouri = Column(String)
    wisconsin = Column(String)
    nevada = Column(String)
    hawaii = Column(String)
    other_street = Column(String)
    louisiana1 = Column(String)
    michigan = Column(String)
    ffm_date_2023 = Column(String)
    ffm_date_2022 = Column(String)
    bank_name = Column(String)
    lead_source = Column(String)
    assigns_commissions = Column(String)
    middle_name = Column(String)
    email = Column(String)
    visitor_score = Column(String)
    wyoming = Column(String)
    ga_agent = Column(String)
    other_state = Column(String)
    last_activity_time = Column(String)
    crm_added_date = Column(String)
    exchange_rate = Column(String)
    nickname = Column(String)
    reporting_to = Column(String)
    ffm_npn_valid = Column(String)
    marketing_allowance_balance = Column(String)
    other_city = Column(String)
    new_jersey = Column(String)
    new_york = Column(String)
    dmp_subdomain = Column(String)
    kansas = Column(String)
    positive_touch_point_score = Column(String)
    pennsylvania = Column(String)
    home_phone = Column(String)
    other_site = Column(String)
    preferred_language = Column(String)
    gdriveextension__olddrive_folder_id = Column(String)
    score = Column(String)
    iowa = Column(String)
    retail_address_street = Column(String)
    state = Column(String)
    retail_address_city = Column(String)
    texas = Column(String)
    overrides = Column(String)
    retail_location = Column(String)
    vermont = Column(String)
    shop_2022 = Column(String)
    mailing_zip = Column(String)
    reports_to = Column(String)
    twitter = Column(String)
    west_virginia = Column(String)
    alabama = Column(String)
    npn = Column(String)
    shop_2023 = Column(String)
    nebraska = Column(String)
    asst_phone = Column(String)
    marketing_allowance = Column(String)
    modified_by = Column(String)
    colorado = Column(String)
    alaska = Column(String)
    agency_dba = Column(String)
    gdriveextension__drive_url = Column(String)
    modified_time = Column(String)
    ffm_npn_verified = Column(String)
    date_of_birth = Column(String)
    title = Column(String)
    minnesota = Column(String)
    company_site = Column(String)
    first_visited_time = Column(String)
    north_dakota = Column(String)
    referrer = Column(String)
    ohio = Column(String)
    support_rep = Column(String)
    fax = Column(String)
    assignee_npn = Column(String)
    bank_routing_no = Column(String)
    mailing_state = Column(String)
    expiration_date = Column(String)
    ffm_user_id = Column(String)
    gdriveextension__drive_folder_id = Column(String)
    other_country = Column(String)
    utah = Column(String)
    south_dakota = Column(String)
    ameritas = Column(String)
    connecture_username = Column(String)
    puerto_rico = Column(String)
    id = Column(String)
    worldtrips = Column(String)
    arizona = Column(String)
    affiliation = Column(String)
    ahip_2023 = Column(String)
    montana = Column(String)
    new_hampshire = Column(String)
    created_time = Column(String)
    ahip_date1 = Column(String)
    kentucky = Column(String)
    delaware = Column(String)
    florida = Column(String)
    healthsherpa = Column(String)
    negative_score = Column(String)
    suffix = Column(String)
    connecticut = Column(String)
    last_visited_time = Column(String)
    south_carolina = Column(String)
    created_by = Column(String)
    last_call = Column(String)
    virginia = Column(String)
    sales_director = Column(String)
    positive_score = Column(String)
    description = Column(String)
    geoblue = Column(String)
    responsible_agent = Column(String)
    ffm_2023 = Column(String)
    salutation = Column(String)
    ffm_2022 = Column(String)
    retail_address_state = Column(String)
    ffm_2021 = Column(String)
    massachusetts = Column(String)
    last_ffm_search = Column(String)
    ethos_purl = Column(String)
    email_opt_out = Column(String)
    w9_needed = Column(String)
    ffm_date1 = Column(String)
    email_bounced = Column(String)
    mobile = Column(String)
    type = Column(String)
    retail_address_county = Column(String)
    ffm_congrats_sms_sent = Column(String)
    tag = Column(String)
    other_phone = Column(String)
    retail_address_zip = Column(String)
    e_o_needed = Column(String)
    ffm = Column(String)
    ahip = Column(String)
    mailing_county = Column(String)
    north_carolina = Column(String)
    mailing_country = Column(String)
    myadmin = Column(String)
    days_visited = Column(String)
    active_since = Column(String)
    pronunciation = Column(String)
    market_interests = Column(String)
    secondary_email = Column(String)
    recruiter = Column(String)
    district_of_columbia = Column(String)
    oregon = Column(String)
    connecture_status = Column(String)
    vendor_name = Column(String)
    tennessee = Column(String)
    maine = Column(String)
    first_name = Column(String)
    bank_account_name = Column(String)
    first_licensed = Column(String)
    bank_updated = Column(String)
    phone = Column(String)
    ahip1 = Column(String)
    mailing_street_2 = Column(String)
    new_mexico = Column(String)
    apppintagents_com = Column(String)
    bank_account_no = Column(String)
    mailing_city = Column(String)
    ahip_date = Column(String)
    ssn = Column(String)
    retail_address_street_2 = Column(String)
    last_name = Column(String)
    ffm1 = Column(String)
    ffm_date = Column(String)
    ffm_npn_valid1 = Column(String)
    responsible_agency = Column(String)
    prospector = Column(String)
    overrides2 = Column(String)
    full_name = Column(String)
    sub_entity_id = Column(String)
    cms_termed = Column(String)

    def __repr__(self):
        values = {c.name: getattr(self, c.name) for c in self.__table__.columns}
        return f"<Agents {values}>"


class AgentFinancial(Base):
    __tablename__ = "agent_financial"
    __table_args__ = {"schema": "wpo"}

    # Using String for UUIDs to maintain cross-db compatibility
    pk_id = Column(UNIQUEIDENTIFIER, primary_key=True, default=uuid.uuid4)
    agent_id = Column(
        UNIQUEIDENTIFIER,
        ForeignKey("wpo.lup_agents.pk_id"),
        nullable=False,
    )

    bank_name = Column(String, nullable=False)
    routing_number = Column(String, nullable=False)
    account_number = Column(String, nullable=False)

    is_primary = Column(Boolean, nullable=False, server_default=sa_text("false"))
    def __repr__(self):
        values = {c.name: getattr(self, c.name) for c in self.__table__.columns}
        return f"<AgentFinancial {values}>"

