from app.models.BaseClasses import Base
from sqlalchemy import Column, String
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
import uuid


class AgentContracts(Base):
    __tablename__ = "lup_agents_contracts"
    __table_args__ = {"schema": "wpo"}


    pk_id = Column(UNIQUEIDENTIFIER, primary_key=True, default=uuid.uuid4, nullable=False)
    
    company_id = Column(String)
    company_name = Column(String)
    owner = Column(String)
    email = Column(String)
    date_confirmed = Column(String)
    added_to_connecture = Column(String)
    agent_status = Column(String)
    invite_type = Column(String)
    parent_contract = Column(String)
    override_schedule = Column(String)
    added_to_connecture1 = Column(String)
    name = Column(String)
    last_activity_time = Column(String)
    exchange_rate = Column(String)
    currency = Column(String)
    day_10_reminder_sent = Column(String)
    id = Column(String)
    carrier = Column(String)
    appointment_type = Column(String)
    affiliation = Column(String)
    medicare_rts = Column(String)
    status = Column(String)
    agent = Column(String)
    appointed_states = Column(String)
    assignee = Column(String)
    assigns_commissions1 = Column(String)
    release_type = Column(String)
    created_time = Column(String)
    preferred_language = Column(String)
    life = Column(String)
    created_by = Column(String)
    secondary_email = Column(String)
    group = Column(String)
    upline = Column(String)
    field_sales_director = Column(String)
    writing_number = Column(String)
    npn = Column(String)
    source = Column(String)
    rts_date1 = Column(String)
    first_name = Column(String)
    modified_by = Column(String)
    ifp = Column(String)
    day_3_reminder_sent = Column(String)
    phone = Column(String)
    top_upline = Column(String)
    email_opt_out = Column(String)
    medicare_rts_2023 = Column(String)
    or_schedule_date = Column(String)
    override_sch = Column(String)
    modified_time = Column(String)
    medicare = Column(String)
    status_date = Column(String)
    google_drive_id = Column(String)
    requested_states = Column(String)
    daily_update_sent = Column(String)
    last_name = Column(String)
    unique_id = Column(String)
    schedule = Column(String)
    tag = Column(String)
    current_or_sch = Column(String)
    assigns_commissions = Column(String)
    upline_npn = Column(String)
    top_upline_npn = Column(String)
    recruiter_fsd_confirm = Column(String)
    marketer = Column(String)
    current_or_sch_status = Column(String)
    amerilife_affiliate_form_name = Column(String)
    or_sch = Column(String)
    med_or_sch = Column(String)

    def __repr__(self):
        return f"<LupAgentsContracts(pk_id='{self.pk_id}', company_id='{self.company_id}', email='{self.email}')>"
