from sqlalchemy import Column, String, Boolean, Text ,Date, Integer
from app.models.BaseClasses import Base
from sqlalchemy.dialects.postgresql import ARRAY, UUID, JSONB
from sqlalchemy.sql import text

class AgentMasterContracts(Base):
    __tablename__ = "lup_master_agents_contracts"
    __table_args__ = {"schema": "wpo"}

    company_id = Column(String(20))
    company_name = Column(String(100))
    carrier_id = Column(String(25))
    carrier_name = Column(String(100))
    contract_id_crm = Column(Text)
    name = Column("name", String(100))
    status = Column(String(50))
    writing_number = Column(Text)
    product_type = Column(Text)
    plan_year = Column(String(10))
    com_schedule = Column(Text)
    or_schedule = Column(Text)
    npn = Column(String(20))
    appointment_type = Column(Text)
    parent_contract = Column(Text)
    upline = Column(Text)
    upline_npn = Column(Text)
    top_upline = Column(Text)
    top_upline_npn = Column(Text)
    field_sales_director = Column(Text)
    recruiter_fsd_confirm = Column(Text)
    agent_id_crm = Column(Text)
    first_name = Column(Text)
    last_name = Column(Text)
    agent_name = Column(Text)
    recruiter = Column(Text)
    assigns_commissions = Column(Text)
    assignee = Column(Text)
    assignee_npn = Column(Text)
    overrides1 = Column(Text)
    type = Column("type", Text)
    responsible_agent = Column(Text)
    or_exclusion = Column(Text)
    level_cat = Column(Text)
    start_datetime = Column(Text)
    end_datetime = Column(Text)
    source_system = Column(Text)
    pk_id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        nullable=False
    )
    seq_id = Column(
        Integer,
        nullable=False,
        autoincrement=True,
        server_default=text("nextval('wpo.lup_master_agents_contracts_seq_id_seq'::regclass)")
        # GENERATED BY DEFAULT AS IDENTITY handled by DB
    )
    sub_entity_id = Column(String(20))
    notes = Column(Text)
    pause_commission_payment = Column(Boolean)
    compliance_event_date = Column(Text)
    requested_state = Column(
        JSONB,
        nullable=True,
        server_default=text("'{}'::jsonb")
    )
    appointed_state = Column(
        JSONB,
        nullable=True,
        server_default=text("'{}'::jsonb")
    )
    created_date = Column(Date)
    
    def __repr__(self):
        return (
            f"<AgentMasterContracts("
            f"pk_id={self.pk_id}, "
            f"company_id={self.company_id}, "
            f"company_name={self.company_name}, "
            f"carrier_id={self.carrier_id}, "
            f"carrier_name={self.carrier_name}, "
            f"contract_id_crm={self.contract_id_crm}, "
            f"name={self.name}, "
            f"status={self.status}, "
            f"npn={self.npn}, "
            f"agent_id_crm={self.agent_id_crm}"
            f")>"
        )