from app.models.BaseClasses import Base
from sqlalchemy import Column, String, DateTime, Text
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER
import uuid
from datetime import datetime, timezone


class CenteneSupplemental(Base):
    __tablename__ = "centene_supplemental"
    __table_args__ = {"schema": "wpo"}

    id = Column(
        UNIQUEIDENTIFIER,
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )

    # Existing Fields
    cnc_member_id = Column(String(50), nullable=False)
    medicaid_nbr = Column(String(50), nullable=True)
    mbi = Column(String(50), nullable=True)
    last_name = Column(String(50), nullable=True)
    first_name = Column(String(50), nullable=True)
    dob = Column(String(50), nullable=True)
    dos = Column(String(50), nullable=False)
    icd_px1 = Column(String(50), nullable=True)
    icd_px2 = Column(String(50), nullable=True)
    icd_dx_pri = Column(String(50), nullable=True)
    icd_dx_sec1 = Column(String(50), nullable=True)
    icd_dx_sec2 = Column(String(50), nullable=True)
    icd_dx_sec3 = Column(String(50), nullable=True)
    icd_dx_sec4 = Column(String(50), nullable=True)
    icd_version = Column(String(50), nullable=True)
    cpt_px = Column(String(50), nullable=True)
    hcpc_ps_px = Column(String(50), nullable=True)
    hcfa_pos = Column(String(50), nullable=True)
    cvx = Column(String(50), nullable=True)
    bp_systolic = Column(String(50), nullable=True)
    bp_diastolic = Column(String(50), nullable=True)
    bmi_value = Column(String(50), nullable=True)
    provider_npi = Column(String(50), nullable=True)
    provider_tin = Column(String(50), nullable=True)
    taxonomy_code = Column(String(70), nullable=True)
    cms_specialty_code = Column(String(50), nullable=True)
    pdf_name = Column(Text, nullable=True)
    cnc_plan_code = Column(String(50), nullable=True)
    hichn = Column(String(50), nullable=True)
    middle_name = Column(String(50), nullable=True)
    claim_number = Column(String(80), nullable=True)
    dos_thru = Column(String(50), nullable=True)
    event_diagnosis = Column(String(200), nullable=True)
    icd_dx_sec5 = Column(String(50), nullable=True)
    icd_dx_sec6 = Column(String(50), nullable=True)
    icd_dx_sec7 = Column(String(50), nullable=True)
    icd_dx_sec8 = Column(String(50), nullable=True)
    icd_dx_sec9 = Column(String(50), nullable=True)
    icd_dx_sec10 = Column(String(50), nullable=True)
    icd_dx_sec11 = Column(String(50), nullable=True)
    icd_dx_sec12 = Column(String(50), nullable=True)
    icd_dx_sec13 = Column(String(50), nullable=True)
    icd_dx_sec14 = Column(String(50), nullable=True)
    icd_dx_sec15 = Column(String(50), nullable=True)
    icd_dx_sec16 = Column(String(50), nullable=True)
    icd_dx_sec17 = Column(String(50), nullable=True)
    icd_dx_sec18 = Column(String(50), nullable=True)
    icd_dx_sec19 = Column(String(50), nullable=True)
    icd_dx_sec20 = Column(String(50), nullable=True)
    icd_dx_sec21 = Column(String(50), nullable=True)
    icd_dx_sec22 = Column(String(50), nullable=True)
    icd_dx_sec23 = Column(String(50), nullable=True)
    icd_dx_sec24 = Column(String(50), nullable=True)
    icd_dx_sec25 = Column(String(50), nullable=True)
    icd_dx_sec26 = Column(String(50), nullable=True)
    icd_dx_sec27 = Column(String(50), nullable=True)
    icd_dx_sec28 = Column(String(50), nullable=True)
    icd_dx_sec29 = Column(String(50), nullable=True)
    icd_dx_sec30 = Column(String(50), nullable=True)
    icd_dx_sec31 = Column(String(50), nullable=True)
    icd_dx_sec32 = Column(String(50), nullable=True)
    icd_dx_sec33 = Column(String(50), nullable=True)
    icd_dx_sec34 = Column(String(50), nullable=True)
    icd_dx_sec35 = Column(String(50), nullable=True)
    icd_dx_sec36 = Column(String(50), nullable=True)
    icd_dx_sec37 = Column(String(50), nullable=True)
    icd_dx_sec38 = Column(String(50), nullable=True)
    icd_dx_sec39 = Column(String(50), nullable=True)
    cpt_mod = Column(String(50), nullable=True)
    hcpc_ps_mod = Column(String(50), nullable=True)
    ub_revenue_code = Column(String(50), nullable=True)
    tob = Column(String(50), nullable=True)
    hcfapos = Column(String(50), nullable=True)
    loinc = Column(String(50), nullable=True)
    loinc_answer = Column(String(15), nullable=True)
    snomed = Column(String(50), nullable=True)
    result = Column(String(50), nullable=True)
    pos_neg_result = Column(String(50), nullable=True)
    claim_alt_id1 = Column(String(255), nullable=True)
    claim_alt_id2 = Column(String(255), nullable=True)
    provider_name = Column(String(179), nullable=True)
    provider_address1 = Column(String(50), nullable=True)
    provider_address2 = Column(String(50), nullable=True)
    provider_city = Column(String(50), nullable=True)
    provider_state = Column(String(50), nullable=True)
    provider_zipcode = Column(String(50), nullable=True)
    provider_phone = Column(String(50), nullable=True)
    intake_type = Column(String(50), nullable=True)
    ocr_text = Column(Text, nullable=True)
    full_name = Column(String(50), nullable=True)
    subjective = Column(Text, nullable=True)
    chief_complaint = Column(Text, nullable=True)
    hpi = Column(Text, nullable=True)
    ros = Column(Text, nullable=True)
    medical_history = Column(Text, nullable=True)
    family_history = Column(Text, nullable=True)
    social_history = Column(Text, nullable=True)
    medications = Column(Text, nullable=True)
    allergies = Column(Text, nullable=True)
    vitals = Column(Text, nullable=True)
    physical_examination = Column(Text, nullable=True)
    assessment = Column(Text, nullable=True)
    plan = Column(Text, nullable=True)
    treatment = Column(Text, nullable=True)
    recommendations = Column(Text, nullable=True)
    preventive_medicine = Column(Text, nullable=True)
    procedure_codes = Column(Text, nullable=True)
    notes = Column(Text, nullable=True)
    reason_of_visit = Column(Text, nullable=True)
    height = Column(String(50), nullable=True)
    weight = Column(String(50), nullable=True)
    bmi = Column(String(50), nullable=True)
    temperature = Column(String(50), nullable=True)
    heart_rate = Column(String(50), nullable=True)
    result_category = Column(Text, nullable=True)
    entity_id = Column(String(50), nullable=True)
    sub_entity_id = Column(String(50), nullable=True)


    def __repr__(self):
        return f"<CenteneSupplemental(id={self.id}, cnc_member_id='{self.cnc_member_id}', dos='{self.dos}', pdf_name='{self.pdf_name}')>"
