from sqlalchemy import Column, String, Integer
from app.models.BaseClasses import Base  # adjust path if needed


class npi_registry(Base):
    __tablename__ = "npi_registry"
    __table_args__ = {"schema": "wpo"}
 
    npi = Column("NPI", String, primary_key=True)
    entity_type_code = Column("Entity Type Code", String, nullable=True)
    replacement_npi = Column("Replacement NPI", String, nullable=True)
    employer_identification_number = Column("Employer Identification Number (EIN)", String, nullable=True)
    provider_organization_name = Column("Provider Organization Name (Legal Business Name)", String, nullable=True)
    provider_last_name = Column("Provider Last Name (Legal Name)", String, nullable=True)
    provider_first_name = Column("Provider First Name", String, nullable=True)
    provider_middle_name = Column("Provider Middle Name", String, nullable=True)
    provider_name_prefix_text = Column("Provider Name Prefix Text", String, nullable=True)
    provider_name_suffix_text = Column("Provider Name Suffix Text", String, nullable=True)
    provider_credential_text = Column("Provider Credential Text", String, nullable=True)
    provider_other_organization_name = Column("Provider Other Organization Name", String, nullable=True)
    provider_other_organization_name_type_code = Column("Provider Other Organization Name Type Code", String, nullable=True)
    provider_other_last_name = Column("Provider Other Last Name", String, nullable=True)
    provider_other_first_name = Column("Provider Other First Name", String, nullable=True)
    provider_other_middle_name = Column("Provider Other Middle Name", String, nullable=True)
    provider_other_name_prefix_text = Column("Provider Other Name Prefix Text", String, nullable=True)
    provider_other_name_suffix_text = Column("Provider Other Name Suffix Text", String, nullable=True)
    provider_other_credential_text = Column("Provider Other Credential Text", String, nullable=True)
    provider_other_last_name_type_code = Column("Provider Other Last Name Type Code", String, nullable=True)
    provider_first_line_business_mailing_address = Column("Provider First Line Business Mailing Address", String, nullable=True)
    provider_second_line_business_mailing_address = Column("Provider Second Line Business Mailing Address", String, nullable=True)
    provider_business_mailing_address_city_name = Column("Provider Business Mailing Address City Name", String, nullable=True)
    provider_business_mailing_address_state_name = Column("Provider Business Mailing Address State Name", String, nullable=True)
    provider_business_mailing_address_postal_code = Column("Provider Business Mailing Address Postal Code", String, nullable=True)
    provider_business_mailing_address_country_code = Column("Provider Business Mailing Address Country Code (If outside U.S.)", String, nullable=True)
    provider_business_mailing_address_telephone_number = Column("Provider Business Mailing Address Telephone Number", String, nullable=True)
    provider_business_mailing_address_fax_number = Column("Provider Business Mailing Address Fax Number", String, nullable=True)
    provider_first_line_business_practice_location_address = Column("Provider First Line Business Practice Location Address", String, nullable=True)
    provider_second_line_business_practice_location_address = Column("Provider Second Line Business Practice Location Address", String, nullable=True)
    provider_business_practice_location_address_city_name = Column("Provider Business Practice Location Address City Name", String, nullable=True)
    provider_business_practice_location_address_state_name = Column("Provider Business Practice Location Address State Name", String, nullable=True)
    provider_business_practice_location_address_postal_code = Column("Provider Business Practice Location Address Postal Code", String, nullable=True)
    provider_business_practice_location_address_country_code = Column("Provider Business Practice Location Address Country Code (If outside U.S.)", String, nullable=True)
    provider_business_practice_location_address_telephone_number = Column("Provider Business Practice Location Address Telephone Number", String, nullable=True)
    provider_business_practice_location_address_fax_number = Column("Provider Business Practice Location Address Fax Number", String, nullable=True)
    provider_enumeration_date = Column("Provider Enumeration Date", String, nullable=True)
    last_update_date = Column("Last Update Date", String, nullable=True)
    npi_deactivation_reason_code = Column("NPI Deactivation Reason Code", String, nullable=True)
    npi_deactivation_date = Column("NPI Deactivation Date", String, nullable=True)
    npi_reactivation_date = Column("NPI Reactivation Date", String, nullable=True)
    provider_gender_code = Column("Provider Gender Code", String, nullable=True)
    authorized_official_last_name = Column("Authorized Official Last Name", String, nullable=True)
    authorized_official_first_name = Column("Authorized Official First Name", String, nullable=True)
    authorized_official_middle_name = Column("Authorized Official Middle Name", String, nullable=True)
    authorized_official_title_or_position = Column("Authorized Official Title or Position", String, nullable=True)
    authorized_official_telephone_number = Column("Authorized Official Telephone Number", String, nullable=True)
    healthcare_provider_taxonomy_code_1 = Column("Healthcare Provider Taxonomy Code_1", String, nullable=True)
    provider_license_number_1 = Column("Provider License Number_1", String, nullable=True)
    provider_license_number_state_code_1 = Column("Provider License Number State Code_1", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_1 = Column("Healthcare Provider Primary Taxonomy Switch_1", String, nullable=True)
    healthcare_provider_taxonomy_code_2 = Column("Healthcare Provider Taxonomy Code_2", String, nullable=True)
    provider_license_number_2 = Column("Provider License Number_2", String, nullable=True)
    provider_license_number_state_code_2 = Column("Provider License Number State Code_2", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_2 = Column("Healthcare Provider Primary Taxonomy Switch_2", String, nullable=True)
    healthcare_provider_taxonomy_code_3 = Column("Healthcare Provider Taxonomy Code_3", String, nullable=True)
    provider_license_number_3 = Column("Provider License Number_3", String, nullable=True)
    provider_license_number_state_code_3 = Column("Provider License Number State Code_3", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_3 = Column("Healthcare Provider Primary Taxonomy Switch_3", String, nullable=True)
    healthcare_provider_taxonomy_code_4 = Column("Healthcare Provider Taxonomy Code_4", String, nullable=True)
    provider_license_number_4 = Column("Provider License Number_4", String, nullable=True)
    provider_license_number_state_code_4 = Column("Provider License Number State Code_4", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_4 = Column("Healthcare Provider Primary Taxonomy Switch_4", String, nullable=True)
    healthcare_provider_taxonomy_code_5 = Column("Healthcare Provider Taxonomy Code_5", String, nullable=True)
    provider_license_number_5 = Column("Provider License Number_5", String, nullable=True)
    provider_license_number_state_code_5 = Column("Provider License Number State Code_5", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_5 = Column("Healthcare Provider Primary Taxonomy Switch_5", String, nullable=True)
    healthcare_provider_taxonomy_code_6 = Column("Healthcare Provider Taxonomy Code_6", String, nullable=True)
    provider_license_number_6 = Column("Provider License Number_6", String, nullable=True)
    provider_license_number_state_code_6 = Column("Provider License Number State Code_6", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_6 = Column("Healthcare Provider Primary Taxonomy Switch_6", String, nullable=True)
    healthcare_provider_taxonomy_code_7 = Column("Healthcare Provider Taxonomy Code_7", String, nullable=True)
    provider_license_number_7 = Column("Provider License Number_7", String, nullable=True)
    provider_license_number_state_code_7 = Column("Provider License Number State Code_7", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_7 = Column("Healthcare Provider Primary Taxonomy Switch_7", String, nullable=True)
    healthcare_provider_taxonomy_code_8 = Column("Healthcare Provider Taxonomy Code_8", String, nullable=True)
    provider_license_number_8 = Column("Provider License Number_8", String, nullable=True)
    provider_license_number_state_code_8 = Column("Provider License Number State Code_8", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_8 = Column("Healthcare Provider Primary Taxonomy Switch_8", String, nullable=True)
    healthcare_provider_taxonomy_code_9 = Column("Healthcare Provider Taxonomy Code_9", String, nullable=True)
    provider_license_number_9 = Column("Provider License Number_9", String, nullable=True)
    provider_license_number_state_code_9 = Column("Provider License Number State Code_9", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_9 = Column("Healthcare Provider Primary Taxonomy Switch_9", String, nullable=True)
    healthcare_provider_taxonomy_code_10 = Column("Healthcare Provider Taxonomy Code_10", String, nullable=True)
    provider_license_number_10 = Column("Provider License Number_10", String, nullable=True)
    provider_license_number_state_code_10 = Column("Provider License Number State Code_10", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_10 = Column("Healthcare Provider Primary Taxonomy Switch_10", String, nullable=True)
    healthcare_provider_taxonomy_code_11 = Column("Healthcare Provider Taxonomy Code_11", String, nullable=True)
    provider_license_number_11 = Column("Provider License Number_11", String, nullable=True)
    provider_license_number_state_code_11 = Column("Provider License Number State Code_11", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_11 = Column("Healthcare Provider Primary Taxonomy Switch_11", String, nullable=True)
    healthcare_provider_taxonomy_code_12 = Column("Healthcare Provider Taxonomy Code_12", String, nullable=True)
    provider_license_number_12 = Column("Provider License Number_12", String, nullable=True)
    provider_license_number_state_code_12 = Column("Provider License Number State Code_12", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_12 = Column("Healthcare Provider Primary Taxonomy Switch_12", String, nullable=True)
    healthcare_provider_taxonomy_code_13 = Column("Healthcare Provider Taxonomy Code_13", String, nullable=True)
    provider_license_number_13 = Column("Provider License Number_13", String, nullable=True)
    provider_license_number_state_code_13 = Column("Provider License Number State Code_13", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_13 = Column("Healthcare Provider Primary Taxonomy Switch_13", String, nullable=True)
    healthcare_provider_taxonomy_code_14 = Column("Healthcare Provider Taxonomy Code_14", String, nullable=True)
    provider_license_number_14 = Column("Provider License Number_14", String, nullable=True)
    provider_license_number_state_code_14 = Column("Provider License Number State Code_14", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_14 = Column("Healthcare Provider Primary Taxonomy Switch_14", String, nullable=True)
    healthcare_provider_taxonomy_code_15 = Column("Healthcare Provider Taxonomy Code_15", String, nullable=True)
    provider_license_number_15 = Column("Provider License Number_15", String, nullable=True)
    provider_license_number_state_code_15 = Column("Provider License Number State Code_15", String, nullable=True)
    healthcare_provider_primary_taxonomy_switch_15 = Column("Healthcare Provider Primary Taxonomy Switch_15", String, nullable=True)
    other_provider_identifier_1 = Column("Other Provider Identifier_1", String, nullable=True)
    other_provider_identifier_type_code_1 = Column("Other Provider Identifier Type Code_1", String, nullable=True)
    other_provider_identifier_state_1 = Column("Other Provider Identifier State_1", String, nullable=True)
    other_provider_identifier_issuer_1 = Column("Other Provider Identifier Issuer_1", String, nullable=True)
    other_provider_identifier_2 = Column("Other Provider Identifier_2", String, nullable=True)
    other_provider_identifier_type_code_2 = Column("Other Provider Identifier Type Code_2", String, nullable=True)
    other_provider_identifier_state_2 = Column("Other Provider Identifier State_2", String, nullable=True)
    other_provider_identifier_issuer_2 = Column("Other Provider Identifier Issuer_2", String, nullable=True)
    other_provider_identifier_3 = Column("Other Provider Identifier_3", String, nullable=True)
    other_provider_identifier_type_code_3 = Column("Other Provider Identifier Type Code_3", String, nullable=True)
    other_provider_identifier_state_3 = Column("Other Provider Identifier State_3", String, nullable=True)
    other_provider_identifier_issuer_3 = Column("Other Provider Identifier Issuer_3", String, nullable=True)
    other_provider_identifier_4 = Column("Other Provider Identifier_4", String, nullable=True)
    other_provider_identifier_type_code_4 = Column("Other Provider Identifier Type Code_4", String, nullable=True)
    other_provider_identifier_state_4 = Column("Other Provider Identifier State_4", String, nullable=True)
    other_provider_identifier_issuer_4 = Column("Other Provider Identifier Issuer_4", String, nullable=True)
    other_provider_identifier_5 = Column("Other Provider Identifier_5", String, nullable=True)
    other_provider_identifier_type_code_5 = Column("Other Provider Identifier Type Code_5", String, nullable=True)
    other_provider_identifier_state_5 = Column("Other Provider Identifier State_5", String, nullable=True)
    other_provider_identifier_issuer_5 = Column("Other Provider Identifier Issuer_5", String, nullable=True)
    other_provider_identifier_6 = Column("Other Provider Identifier_6", String, nullable=True)
    other_provider_identifier_type_code_6 = Column("Other Provider Identifier Type Code_6", String, nullable=True)
    other_provider_identifier_state_6 = Column("Other Provider Identifier State_6", String, nullable=True)
    other_provider_identifier_issuer_6 = Column("Other Provider Identifier Issuer_6", String, nullable=True)
    other_provider_identifier_7 = Column("Other Provider Identifier_7", String, nullable=True)
    other_provider_identifier_type_code_7 = Column("Other Provider Identifier Type Code_7", String, nullable=True)
    other_provider_identifier_state_7 = Column("Other Provider Identifier State_7", String, nullable=True)
    other_provider_identifier_issuer_7 = Column("Other Provider Identifier Issuer_7", String, nullable=True)
    other_provider_identifier_8 = Column("Other Provider Identifier_8", String, nullable=True)
    other_provider_identifier_type_code_8 = Column("Other Provider Identifier Type Code_8", String, nullable=True)
    other_provider_identifier_state_8 = Column("Other Provider Identifier State_8", String, nullable=True)
    other_provider_identifier_issuer_8 = Column("Other Provider Identifier Issuer_8", String, nullable=True)
    other_provider_identifier_9 = Column("Other Provider Identifier_9", String, nullable=True)
    other_provider_identifier_type_code_9 = Column("Other Provider Identifier Type Code_9", String, nullable=True)
    other_provider_identifier_state_9 = Column("Other Provider Identifier State_9", String, nullable=True)
    other_provider_identifier_issuer_9 = Column("Other Provider Identifier Issuer_9", String, nullable=True)
    other_provider_identifier_10 = Column("Other Provider Identifier_10", String, nullable=True)
    other_provider_identifier_type_code_10 = Column("Other Provider Identifier Type Code_10", String, nullable=True)
    other_provider_identifier_state_10 = Column("Other Provider Identifier State_10", String, nullable=True)
    other_provider_identifier_issuer_10 = Column("Other Provider Identifier Issuer_10", String, nullable=True)
    other_provider_identifier_11 = Column("Other Provider Identifier_11", String, nullable=True)
    other_provider_identifier_type_code_11 = Column("Other Provider Identifier Type Code_11", String, nullable=True)
    other_provider_identifier_state_11 = Column("Other Provider Identifier State_11", String, nullable=True)
    other_provider_identifier_issuer_11 = Column("Other Provider Identifier Issuer_11", String, nullable=True)
    other_provider_identifier_12 = Column("Other Provider Identifier_12", String, nullable=True)
    other_provider_identifier_type_code_12 = Column("Other Provider Identifier Type Code_12", String, nullable=True)
    other_provider_identifier_state_12 = Column("Other Provider Identifier State_12", String, nullable=True)
    other_provider_identifier_issuer_12 = Column("Other Provider Identifier Issuer_12", String, nullable=True)
    other_provider_identifier_13 = Column("Other Provider Identifier_13", String, nullable=True)
    other_provider_identifier_type_code_13 = Column("Other Provider Identifier Type Code_13", String, nullable=True)
    other_provider_identifier_state_13 = Column("Other Provider Identifier State_13", String, nullable=True)
    other_provider_identifier_issuer_13 = Column("Other Provider Identifier Issuer_13", String, nullable=True)
    other_provider_identifier_14 = Column("Other Provider Identifier_14", String, nullable=True)
    other_provider_identifier_type_code_14 = Column("Other Provider Identifier Type Code_14", String, nullable=True)
    other_provider_identifier_state_14 = Column("Other Provider Identifier State_14", String, nullable=True)
    other_provider_identifier_issuer_14 = Column("Other Provider Identifier Issuer_14", String, nullable=True)
    other_provider_identifier_15 = Column("Other Provider Identifier_15", String, nullable=True)
    other_provider_identifier_type_code_15 = Column("Other Provider Identifier Type Code_15", String, nullable=True)
    other_provider_identifier_state_15 = Column("Other Provider Identifier State_15", String, nullable=True)
    other_provider_identifier_issuer_15 = Column("Other Provider Identifier Issuer_15", String, nullable=True)
    other_provider_identifier_16 = Column("Other Provider Identifier_16", String, nullable=True)
    other_provider_identifier_type_code_16 = Column("Other Provider Identifier Type Code_16", String, nullable=True)
    other_provider_identifier_state_16 = Column("Other Provider Identifier State_16", String, nullable=True)
    other_provider_identifier_issuer_16 = Column("Other Provider Identifier Issuer_16", String, nullable=True)
    other_provider_identifier_17 = Column("Other Provider Identifier_17", String, nullable=True)
    other_provider_identifier_type_code_17 = Column("Other Provider Identifier Type Code_17", String, nullable=True)
    other_provider_identifier_state_17 = Column("Other Provider Identifier State_17", String, nullable=True)
    other_provider_identifier_issuer_17 = Column("Other Provider Identifier Issuer_17", String, nullable=True)
    other_provider_identifier_18 = Column("Other Provider Identifier_18", String, nullable=True)
    other_provider_identifier_type_code_18 = Column("Other Provider Identifier Type Code_18", String, nullable=True)
    other_provider_identifier_state_18 = Column("Other Provider Identifier State_18", String, nullable=True)
    other_provider_identifier_issuer_18 = Column("Other Provider Identifier Issuer_18", String, nullable=True)
    other_provider_identifier_19 = Column("Other Provider Identifier_19", String, nullable=True)
    other_provider_identifier_type_code_19 = Column("Other Provider Identifier Type Code_19", String, nullable=True)
    other_provider_identifier_state_19 = Column("Other Provider Identifier State_19", String, nullable=True)
    other_provider_identifier_issuer_19 = Column("Other Provider Identifier Issuer_19", String, nullable=True)
    other_provider_identifier_20 = Column("Other Provider Identifier_20", String, nullable=True)
    other_provider_identifier_type_code_20 = Column("Other Provider Identifier Type Code_20", String, nullable=True)
    other_provider_identifier_state_20 = Column("Other Provider Identifier State_20", String, nullable=True)
    other_provider_identifier_issuer_20 = Column("Other Provider Identifier Issuer_20", String, nullable=True)
    other_provider_identifier_21 = Column("Other Provider Identifier_21", String, nullable=True)
    other_provider_identifier_type_code_21 = Column("Other Provider Identifier Type Code_21", String, nullable=True)
    other_provider_identifier_state_21 = Column("Other Provider Identifier State_21", String, nullable=True)
    other_provider_identifier_issuer_21 = Column("Other Provider Identifier Issuer_21", String, nullable=True)
    other_provider_identifier_22 = Column("Other Provider Identifier_22", String, nullable=True)
    other_provider_identifier_type_code_22 = Column("Other Provider Identifier Type Code_22", String, nullable=True)
    other_provider_identifier_state_22 = Column("Other Provider Identifier State_22", String, nullable=True)
    other_provider_identifier_issuer_22 = Column("Other Provider Identifier Issuer_22", String, nullable=True)
    other_provider_identifier_23 = Column("Other Provider Identifier_23", String, nullable=True)
    other_provider_identifier_type_code_23 = Column("Other Provider Identifier Type Code_23", String, nullable=True)
    other_provider_identifier_state_23 = Column("Other Provider Identifier State_23", String, nullable=True)
    other_provider_identifier_issuer_23 = Column("Other Provider Identifier Issuer_23", String, nullable=True)
    other_provider_identifier_24 = Column("Other Provider Identifier_24", String, nullable=True)
    other_provider_identifier_type_code_24 = Column("Other Provider Identifier Type Code_24", String, nullable=True)
    other_provider_identifier_state_24 = Column("Other Provider Identifier State_24", String, nullable=True)
    other_provider_identifier_issuer_24 = Column("Other Provider Identifier Issuer_24", String, nullable=True)
    other_provider_identifier_25 = Column("Other Provider Identifier_25", String, nullable=True)
    other_provider_identifier_type_code_25 = Column("Other Provider Identifier Type Code_25", String, nullable=True)
    other_provider_identifier_state_25 = Column("Other Provider Identifier State_25", String, nullable=True)
    other_provider_identifier_issuer_25 = Column("Other Provider Identifier Issuer_25", String, nullable=True)
    other_provider_identifier_26 = Column("Other Provider Identifier_26", String, nullable=True)
    other_provider_identifier_type_code_26 = Column("Other Provider Identifier Type Code_26", String, nullable=True)
    other_provider_identifier_state_26 = Column("Other Provider Identifier State_26", String, nullable=True)
    other_provider_identifier_issuer_26 = Column("Other Provider Identifier Issuer_26", String, nullable=True)
    other_provider_identifier_27 = Column("Other Provider Identifier_27", String, nullable=True)
    other_provider_identifier_type_code_27 = Column("Other Provider Identifier Type Code_27", String, nullable=True)
    other_provider_identifier_state_27 = Column("Other Provider Identifier State_27", String, nullable=True)
    other_provider_identifier_issuer_27 = Column("Other Provider Identifier Issuer_27", String, nullable=True)
    other_provider_identifier_28 = Column("Other Provider Identifier_28", String, nullable=True)
    other_provider_identifier_type_code_28 = Column("Other Provider Identifier Type Code_28", String, nullable=True)
    other_provider_identifier_state_28 = Column("Other Provider Identifier State_28", String, nullable=True)
    other_provider_identifier_issuer_28 = Column("Other Provider Identifier Issuer_28", String, nullable=True)
    other_provider_identifier_29 = Column("Other Provider Identifier_29", String, nullable=True)
    other_provider_identifier_type_code_29 = Column("Other Provider Identifier Type Code_29", String, nullable=True)
    other_provider_identifier_state_29 = Column("Other Provider Identifier State_29", String, nullable=True)
    other_provider_identifier_issuer_29 = Column("Other Provider Identifier Issuer_29", String, nullable=True)
    other_provider_identifier_30 = Column("Other Provider Identifier_30", String, nullable=True)
    other_provider_identifier_type_code_30 = Column("Other Provider Identifier Type Code_30", String, nullable=True)
    other_provider_identifier_state_30 = Column("Other Provider Identifier State_30", String, nullable=True)
    other_provider_identifier_issuer_30 = Column("Other Provider Identifier Issuer_30", String, nullable=True)
    other_provider_identifier_31 = Column("Other Provider Identifier_31", String, nullable=True)
    other_provider_identifier_type_code_31 = Column("Other Provider Identifier Type Code_31", String, nullable=True)
    other_provider_identifier_state_31 = Column("Other Provider Identifier State_31", String, nullable=True)
    other_provider_identifier_issuer_31 = Column("Other Provider Identifier Issuer_31", String, nullable=True)
    other_provider_identifier_32 = Column("Other Provider Identifier_32", String, nullable=True)
    other_provider_identifier_type_code_32 = Column("Other Provider Identifier Type Code_32", String, nullable=True)
    other_provider_identifier_state_32 = Column("Other Provider Identifier State_32", String, nullable=True)
    other_provider_identifier_issuer_32 = Column("Other Provider Identifier Issuer_32", String, nullable=True)
    other_provider_identifier_33 = Column("Other Provider Identifier_33", String, nullable=True)
    other_provider_identifier_type_code_33 = Column("Other Provider Identifier Type Code_33", String, nullable=True)
    other_provider_identifier_state_33 = Column("Other Provider Identifier State_33", String, nullable=True)
    other_provider_identifier_issuer_33 = Column("Other Provider Identifier Issuer_33", String, nullable=True)
    other_provider_identifier_34 = Column("Other Provider Identifier_34", String, nullable=True)
    other_provider_identifier_type_code_34 = Column("Other Provider Identifier Type Code_34", String, nullable=True)
    other_provider_identifier_state_34 = Column("Other Provider Identifier State_34", String, nullable=True)
    other_provider_identifier_issuer_34 = Column("Other Provider Identifier Issuer_34", String, nullable=True)
    other_provider_identifier_35 = Column("Other Provider Identifier_35", String, nullable=True)
    other_provider_identifier_type_code_35 = Column("Other Provider Identifier Type Code_35", String, nullable=True)
    other_provider_identifier_state_35 = Column("Other Provider Identifier State_35", String, nullable=True)
    other_provider_identifier_issuer_35 = Column("Other Provider Identifier Issuer_35", String, nullable=True)
    other_provider_identifier_36 = Column("Other Provider Identifier_36", String, nullable=True)
    other_provider_identifier_type_code_36 = Column("Other Provider Identifier Type Code_36", String, nullable=True)
    other_provider_identifier_state_36 = Column("Other Provider Identifier State_36", String, nullable=True)
    other_provider_identifier_issuer_36 = Column("Other Provider Identifier Issuer_36", String, nullable=True)
    other_provider_identifier_37 = Column("Other Provider Identifier_37", String, nullable=True)
    other_provider_identifier_type_code_37 = Column("Other Provider Identifier Type Code_37", String, nullable=True)
    other_provider_identifier_state_37 = Column("Other Provider Identifier State_37", String, nullable=True)
    other_provider_identifier_issuer_37 = Column("Other Provider Identifier Issuer_37", String, nullable=True)
    other_provider_identifier_38 = Column("Other Provider Identifier_38", String, nullable=True)
    other_provider_identifier_type_code_38 = Column("Other Provider Identifier Type Code_38", String, nullable=True)
    other_provider_identifier_state_38 = Column("Other Provider Identifier State_38", String, nullable=True)
    other_provider_identifier_issuer_38 = Column("Other Provider Identifier Issuer_38", String, nullable=True)
    other_provider_identifier_39 = Column("Other Provider Identifier_39", String, nullable=True)
    other_provider_identifier_type_code_39 = Column("Other Provider Identifier Type Code_39", String, nullable=True)
    other_provider_identifier_state_39 = Column("Other Provider Identifier State_39", String, nullable=True)
    other_provider_identifier_issuer_39 = Column("Other Provider Identifier Issuer_39", String, nullable=True)
    other_provider_identifier_40 = Column("Other Provider Identifier_40", String, nullable=True)
    other_provider_identifier_type_code_40 = Column("Other Provider Identifier Type Code_40", String, nullable=True)
    other_provider_identifier_state_40 = Column("Other Provider Identifier State_40", String, nullable=True)
    other_provider_identifier_issuer_40 = Column("Other Provider Identifier Issuer_40", String, nullable=True)
    other_provider_identifier_41 = Column("Other Provider Identifier_41", String, nullable=True)
    other_provider_identifier_type_code_41 = Column("Other Provider Identifier Type Code_41", String, nullable=True)
    other_provider_identifier_state_41 = Column("Other Provider Identifier State_41", String, nullable=True)
    other_provider_identifier_issuer_41 = Column("Other Provider Identifier Issuer_41", String, nullable=True)
    other_provider_identifier_42 = Column("Other Provider Identifier_42", String, nullable=True)
    other_provider_identifier_type_code_42 = Column("Other Provider Identifier Type Code_42", String, nullable=True)
    other_provider_identifier_state_42 = Column("Other Provider Identifier State_42", String, nullable=True)
    other_provider_identifier_issuer_42 = Column("Other Provider Identifier Issuer_42", String, nullable=True)
    other_provider_identifier_43 = Column("Other Provider Identifier_43", String, nullable=True)
    other_provider_identifier_type_code_43 = Column("Other Provider Identifier Type Code_43", String, nullable=True)
    other_provider_identifier_state_43 = Column("Other Provider Identifier State_43", String, nullable=True)
    other_provider_identifier_issuer_43 = Column("Other Provider Identifier Issuer_43", String, nullable=True)
    other_provider_identifier_44 = Column("Other Provider Identifier_44", String, nullable=True)
    other_provider_identifier_type_code_44 = Column("Other Provider Identifier Type Code_44", String, nullable=True)
    other_provider_identifier_state_44 = Column("Other Provider Identifier State_44", String, nullable=True)
    other_provider_identifier_issuer_44 = Column("Other Provider Identifier Issuer_44", String, nullable=True)
    other_provider_identifier_45 = Column("Other Provider Identifier_45", String, nullable=True)
    other_provider_identifier_type_code_45 = Column("Other Provider Identifier Type Code_45", String, nullable=True)
    other_provider_identifier_state_45 = Column("Other Provider Identifier State_45", String, nullable=True)
    other_provider_identifier_issuer_45 = Column("Other Provider Identifier Issuer_45", String, nullable=True)
    other_provider_identifier_46 = Column("Other Provider Identifier_46", String, nullable=True)
    other_provider_identifier_type_code_46 = Column("Other Provider Identifier Type Code_46", String, nullable=True)
    other_provider_identifier_state_46 = Column("Other Provider Identifier State_46", String, nullable=True)
    other_provider_identifier_issuer_46 = Column("Other Provider Identifier Issuer_46", String, nullable=True)
    other_provider_identifier_47 = Column("Other Provider Identifier_47", String, nullable=True)
    other_provider_identifier_type_code_47 = Column("Other Provider Identifier Type Code_47", String, nullable=True)
    other_provider_identifier_state_47 = Column("Other Provider Identifier State_47", String, nullable=True)
    other_provider_identifier_issuer_47 = Column("Other Provider Identifier Issuer_47", String, nullable=True)
    other_provider_identifier_48 = Column("Other Provider Identifier_48", String, nullable=True)
    other_provider_identifier_type_code_48 = Column("Other Provider Identifier Type Code_48", String, nullable=True)
    other_provider_identifier_state_48 = Column("Other Provider Identifier State_48", String, nullable=True)
    other_provider_identifier_issuer_48 = Column("Other Provider Identifier Issuer_48", String, nullable=True)
    other_provider_identifier_49 = Column("Other Provider Identifier_49", String, nullable=True)
    other_provider_identifier_type_code_49 = Column("Other Provider Identifier Type Code_49", String, nullable=True)
    other_provider_identifier_state_49 = Column("Other Provider Identifier State_49", String, nullable=True)
    other_provider_identifier_issuer_49 = Column("Other Provider Identifier Issuer_49", String, nullable=True)
    other_provider_identifier_50 = Column("Other Provider Identifier_50", String, nullable=True)
    other_provider_identifier_type_code_50 = Column("Other Provider Identifier Type Code_50", String, nullable=True)
    other_provider_identifier_state_50 = Column("Other Provider Identifier State_50", String, nullable=True)
    other_provider_identifier_issuer_50 = Column("Other Provider Identifier Issuer_50", String, nullable=True)
    is_sole_proprietor = Column("Is Sole Proprietor", String, nullable=True)
    is_organization_subpart = Column("Is Organization Subpart", String, nullable=True)
    parent_organization_lbn = Column("Parent Organization LBN", String, nullable=True)
    parent_organization_tin = Column("Parent Organization TIN", String, nullable=True)
    authorized_official_name_prefix_text = Column("Authorized Official Name Prefix Text", String, nullable=True)
    authorized_official_name_suffix_text = Column("Authorized Official Name Suffix Text", String, nullable=True)
    authorized_official_credential_text = Column("Authorized Official Credential Text", String, nullable=True)
    healthcare_provider_taxonomy_group_1 = Column("Healthcare Provider Taxonomy Group_1", String, nullable=True)
    healthcare_provider_taxonomy_group_2 = Column("Healthcare Provider Taxonomy Group_2", String, nullable=True)
    healthcare_provider_taxonomy_group_3 = Column("Healthcare Provider Taxonomy Group_3", String, nullable=True)
    healthcare_provider_taxonomy_group_4 = Column("Healthcare Provider Taxonomy Group_4", String, nullable=True)
    healthcare_provider_taxonomy_group_5 = Column("Healthcare Provider Taxonomy Group_5", String, nullable=True)
    healthcare_provider_taxonomy_group_6 = Column("Healthcare Provider Taxonomy Group_6", String, nullable=True)
    healthcare_provider_taxonomy_group_7 = Column("Healthcare Provider Taxonomy Group_7", String, nullable=True)
    healthcare_provider_taxonomy_group_8 = Column("Healthcare Provider Taxonomy Group_8", String, nullable=True)
    healthcare_provider_taxonomy_group_9 = Column("Healthcare Provider Taxonomy Group_9", String, nullable=True)
    healthcare_provider_taxonomy_group_10 = Column("Healthcare Provider Taxonomy Group_10", String, nullable=True)
    healthcare_provider_taxonomy_group_11 = Column("Healthcare Provider Taxonomy Group_11", String, nullable=True)
    healthcare_provider_taxonomy_group_12 = Column("Healthcare Provider Taxonomy Group_12", String, nullable=True)
    healthcare_provider_taxonomy_group_13 = Column("Healthcare Provider Taxonomy Group_13", String, nullable=True)
    healthcare_provider_taxonomy_group_14 = Column("Healthcare Provider Taxonomy Group_14", String, nullable=True)
    healthcare_provider_taxonomy_group_15 = Column("Healthcare Provider Taxonomy Group_15", String, nullable=True)
    certification_date = Column("Certification Date", String, nullable=True)
    load_date = Column("load_date", String, nullable=True)
    raw_file_name = Column("raw_file_name", String, nullable=True)
